apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-svc
  namespace: hello-world-python
  labels:
    zarf.dev/connect-name: hello-world-python
spec:
  selector:
    app: hello-world-python
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
